# Generated by Django 3.2 on 2021-04-30 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Purchase date'),
            preserve_default=False,
        ),
    ]
