# Generated by Django 3.2 on 2021-05-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='percentage_difference',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
