# Generated by Django 3.2 on 2021-05-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_budget_percentage_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='theme',
            field=models.CharField(choices=[('Cute Kittens', 'Cute Kittens'), ('Cute Puppies', 'Cute Puppies')], default='Cute Kittens', max_length=12, null=True),
        ),
    ]
