# Generated by Django 3.2 on 2021-05-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_expenditure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='remaining_funds',
            field=models.IntegerField(null=True),
        ),
    ]
