# Generated by Django 3.2 on 2021-05-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_purchasephotos_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='budget',
            name='city',
            field=models.ManyToManyField(to='main_app.City'),
        ),
    ]
