# Generated by Django 3.2 on 2021-05-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_budget_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='theme',
            field=models.CharField(choices=[('Munchkin Kittens', 'Munchkin Kittens'), ('Golden Retriever Puppies', 'Golden Retriever Puppies')], default='Munchkin Kittens', max_length=25, null=True),
        ),
    ]
