# Generated by Django 3.2 on 2021-05-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_budget_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_spent',
            field=models.IntegerField(null=True),
        ),
    ]
