# Generated by Django 3.2 on 2021-05-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_budget_total_spent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='expenditure',
            options={'ordering': ['-date']},
        ),
    ]
